// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_UNKNOWN                  Status = 0
	Status_SUCCESS                  Status = 200
	Status_BAD_REQUEST              Status = 400
	Status_FORBIDDEN                Status = 403
	Status_NOT_FOUND                Status = 404
	Status_REQUEST_ENTITY_TOO_LARGE Status = 413
	Status_INTERNAL_SERVER_ERROR    Status = 500
	Status_NOT_IMPLEMENTED          Status = 501
	Status_SERVICE_UNAVAILABLE      Status = 503
)

var Status_name = map[int32]string{
	0:   "UNKNOWN",
	200: "SUCCESS",
	400: "BAD_REQUEST",
	403: "FORBIDDEN",
	404: "NOT_FOUND",
	413: "REQUEST_ENTITY_TOO_LARGE",
	500: "INTERNAL_SERVER_ERROR",
	501: "NOT_IMPLEMENTED",
	503: "SERVICE_UNAVAILABLE",
}

var Status_value = map[string]int32{
	"UNKNOWN":                  0,
	"SUCCESS":                  200,
	"BAD_REQUEST":              400,
	"FORBIDDEN":                403,
	"NOT_FOUND":                404,
	"REQUEST_ENTITY_TOO_LARGE": 413,
	"INTERNAL_SERVER_ERROR":    500,
	"NOT_IMPLEMENTED":          501,
	"SERVICE_UNAVAILABLE":      503,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type Proposal_ProposalType int32

const (
	Proposal_QUERY         Proposal_ProposalType = 0
	Proposal_INVOKE        Proposal_ProposalType = 1
	Proposal_CONFIG        Proposal_ProposalType = 2
	Proposal_CONFIG_UPDATE Proposal_ProposalType = 3
)

var Proposal_ProposalType_name = map[int32]string{
	0: "QUERY",
	1: "INVOKE",
	2: "CONFIG",
	3: "CONFIG_UPDATE",
}

var Proposal_ProposalType_value = map[string]int32{
	"QUERY":         0,
	"INVOKE":        1,
	"CONFIG":        2,
	"CONFIG_UPDATE": 3,
}

func (x Proposal_ProposalType) String() string {
	return proto.EnumName(Proposal_ProposalType_name, int32(x))
}

func (Proposal_ProposalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Timestamp struct {
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

// ------------------------------- contract.proto1 call -------------------------------
type Proposal struct {
	ProposalType         Proposal_ProposalType `protobuf:"varint,1,opt,name=proposal_type,json=proposalType,proto3,enum=proto.Proposal_ProposalType" json:"proposal_type,omitempty"`
	Timestamp            *Timestamp            `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChannelId            string                `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Contract             string                `protobuf:"bytes,4,opt,name=contract,proto3" json:"contract,omitempty"`
	TxId                 string                `protobuf:"bytes,5,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Creator              []byte                `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Nonce                []byte                `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Args                 [][]byte              `protobuf:"bytes,8,rep,name=args,proto3" json:"args,omitempty"`
	Decorations          map[string][]byte     `protobuf:"bytes,9,rep,name=decorations,proto3" json:"decorations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetProposalType() Proposal_ProposalType {
	if m != nil {
		return m.ProposalType
	}
	return Proposal_QUERY
}

func (m *Proposal) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Proposal) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *Proposal) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Proposal) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Proposal) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *Proposal) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Proposal) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Proposal) GetDecorations() map[string][]byte {
	if m != nil {
		return m.Decorations
	}
	return nil
}

type SignedProposal struct {
	Proposal             *Proposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	Signature            []byte    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignedProposal) Reset()         { *m = SignedProposal{} }
func (m *SignedProposal) String() string { return proto.CompactTextString(m) }
func (*SignedProposal) ProtoMessage()    {}
func (*SignedProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *SignedProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedProposal.Unmarshal(m, b)
}
func (m *SignedProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedProposal.Marshal(b, m, deterministic)
}
func (m *SignedProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedProposal.Merge(m, src)
}
func (m *SignedProposal) XXX_Size() int {
	return xxx_messageInfo_SignedProposal.Size(m)
}
func (m *SignedProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedProposal.DiscardUnknown(m)
}

var xxx_messageInfo_SignedProposal proto.InternalMessageInfo

func (m *SignedProposal) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *SignedProposal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type BatchSubmit struct {
	SignedProposalList   []*SignedProposal `protobuf:"bytes,1,rep,name=signed_proposal_list,json=signedProposalList,proto3" json:"signed_proposal_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BatchSubmit) Reset()         { *m = BatchSubmit{} }
func (m *BatchSubmit) String() string { return proto.CompactTextString(m) }
func (*BatchSubmit) ProtoMessage()    {}
func (*BatchSubmit) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *BatchSubmit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchSubmit.Unmarshal(m, b)
}
func (m *BatchSubmit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchSubmit.Marshal(b, m, deterministic)
}
func (m *BatchSubmit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchSubmit.Merge(m, src)
}
func (m *BatchSubmit) XXX_Size() int {
	return xxx_messageInfo_BatchSubmit.Size(m)
}
func (m *BatchSubmit) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchSubmit.DiscardUnknown(m)
}

var xxx_messageInfo_BatchSubmit proto.InternalMessageInfo

func (m *BatchSubmit) GetSignedProposalList() []*SignedProposal {
	if m != nil {
		return m.SignedProposalList
	}
	return nil
}

type Envelope struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Envelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ProposalResponse struct {
	// A status code that should follow the HTTP status codes.
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// A message associated with the response code.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// A payload that can be used to include metadata with this response.
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposalResponse) Reset()         { *m = ProposalResponse{} }
func (m *ProposalResponse) String() string { return proto.CompactTextString(m) }
func (*ProposalResponse) ProtoMessage()    {}
func (*ProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *ProposalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalResponse.Unmarshal(m, b)
}
func (m *ProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalResponse.Marshal(b, m, deterministic)
}
func (m *ProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalResponse.Merge(m, src)
}
func (m *ProposalResponse) XXX_Size() int {
	return xxx_messageInfo_ProposalResponse.Size(m)
}
func (m *ProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalResponse proto.InternalMessageInfo

func (m *ProposalResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ProposalResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ProposalResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type BatchResponse struct {
	ProposalResponseList []*ProposalResponse `protobuf:"bytes,1,rep,name=proposal_response_list,json=proposalResponseList,proto3" json:"proposal_response_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BatchResponse) Reset()         { *m = BatchResponse{} }
func (m *BatchResponse) String() string { return proto.CompactTextString(m) }
func (*BatchResponse) ProtoMessage()    {}
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *BatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchResponse.Unmarshal(m, b)
}
func (m *BatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchResponse.Marshal(b, m, deterministic)
}
func (m *BatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchResponse.Merge(m, src)
}
func (m *BatchResponse) XXX_Size() int {
	return xxx_messageInfo_BatchResponse.Size(m)
}
func (m *BatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchResponse proto.InternalMessageInfo

func (m *BatchResponse) GetProposalResponseList() []*ProposalResponse {
	if m != nil {
		return m.ProposalResponseList
	}
	return nil
}

//--------------------------------
type ContractEvent struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	TxId                 string   `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	EventName            string   `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractEvent) Reset()         { *m = ContractEvent{} }
func (m *ContractEvent) String() string { return proto.CompactTextString(m) }
func (*ContractEvent) ProtoMessage()    {}
func (*ContractEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *ContractEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractEvent.Unmarshal(m, b)
}
func (m *ContractEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractEvent.Marshal(b, m, deterministic)
}
func (m *ContractEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractEvent.Merge(m, src)
}
func (m *ContractEvent) XXX_Size() int {
	return xxx_messageInfo_ContractEvent.Size(m)
}
func (m *ContractEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ContractEvent proto.InternalMessageInfo

func (m *ContractEvent) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ContractEvent) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *ContractEvent) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *ContractEvent) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// -------------------------------
type Transaction struct {
	SignedProposal       *SignedProposal   `protobuf:"bytes,1,opt,name=signed_proposal,json=signedProposal,proto3" json:"signed_proposal,omitempty"`
	ProposalResponse     *ProposalResponse `protobuf:"bytes,2,opt,name=proposalResponse,proto3" json:"proposalResponse,omitempty"`
	ContractEvent        *ContractEvent    `protobuf:"bytes,3,opt,name=contract_event,json=contractEvent,proto3" json:"contract_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetSignedProposal() *SignedProposal {
	if m != nil {
		return m.SignedProposal
	}
	return nil
}

func (m *Transaction) GetProposalResponse() *ProposalResponse {
	if m != nil {
		return m.ProposalResponse
	}
	return nil
}

func (m *Transaction) GetContractEvent() *ContractEvent {
	if m != nil {
		return m.ContractEvent
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterEnum("proto.Proposal_ProposalType", Proposal_ProposalType_name, Proposal_ProposalType_value)
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*Timestamp)(nil), "proto.Timestamp")
	proto.RegisterType((*Proposal)(nil), "proto.Proposal")
	proto.RegisterMapType((map[string][]byte)(nil), "proto.Proposal.DecorationsEntry")
	proto.RegisterType((*SignedProposal)(nil), "proto.SignedProposal")
	proto.RegisterType((*BatchSubmit)(nil), "proto.BatchSubmit")
	proto.RegisterType((*Envelope)(nil), "proto.Envelope")
	proto.RegisterType((*ProposalResponse)(nil), "proto.ProposalResponse")
	proto.RegisterType((*BatchResponse)(nil), "proto.BatchResponse")
	proto.RegisterType((*ContractEvent)(nil), "proto.ContractEvent")
	proto.RegisterType((*Transaction)(nil), "proto.Transaction")
}

func init() {
	proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206)
}

var fileDescriptor_555bd8c177793206 = []byte{
	// 806 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6a, 0xe3, 0x46,
	0x14, 0x5e, 0x45, 0xf1, 0x8f, 0x8e, 0x6c, 0x67, 0x3a, 0xeb, 0xdd, 0x8a, 0xb0, 0x01, 0xe3, 0x2b,
	0xd3, 0x42, 0x2e, 0xdc, 0x9b, 0xd2, 0x85, 0x05, 0xff, 0x4c, 0x82, 0x58, 0x47, 0xca, 0x8e, 0xe5,
	0x94, 0xa5, 0xb0, 0x62, 0x56, 0x1e, 0xb2, 0xa6, 0xd6, 0x48, 0x68, 0xc6, 0x61, 0xfd, 0x16, 0x85,
	0xf6, 0xb6, 0xef, 0xd2, 0xcb, 0xde, 0xf5, 0x01, 0xfa, 0x1a, 0x2d, 0xbd, 0x2d, 0x1a, 0x4b, 0x8a,
	0xed, 0x12, 0x7a, 0xe5, 0xf3, 0x1d, 0x9d, 0xbf, 0xef, 0x3b, 0x73, 0x0c, 0xad, 0x28, 0x89, 0xe3,
	0x44, 0x5c, 0xa6, 0x59, 0xa2, 0x12, 0x5c, 0xd3, 0x3f, 0xfd, 0x06, 0xd4, 0x48, 0x9c, 0xaa, 0x6d,
	0xff, 0x35, 0x58, 0xc1, 0x2a, 0xe6, 0x52, 0xb1, 0x38, 0xc5, 0x0e, 0x34, 0x24, 0x8f, 0x12, 0xb1,
	0x94, 0x8e, 0xd1, 0x33, 0x06, 0x26, 0x2d, 0x21, 0xee, 0x42, 0x4d, 0x30, 0x91, 0x48, 0xe7, 0xa4,
	0x67, 0x0c, 0x6a, 0x74, 0x07, 0xfa, 0x7f, 0x9a, 0xd0, 0xbc, 0xcd, 0x92, 0x34, 0x91, 0x6c, 0x8d,
	0x47, 0xd0, 0x4e, 0x0b, 0x3b, 0x54, 0xdb, 0x94, 0xeb, 0x12, 0x9d, 0xe1, 0xab, 0x5d, 0xe3, 0xcb,
	0x32, 0xae, 0x32, 0x82, 0x6d, 0xca, 0x69, 0x2b, 0xdd, 0x43, 0xf8, 0x12, 0x2c, 0x55, 0x0e, 0xa3,
	0x3b, 0xd9, 0x43, 0x54, 0xa4, 0x57, 0x43, 0xd2, 0xc7, 0x10, 0x7c, 0x01, 0x10, 0x7d, 0x62, 0x42,
	0xf0, 0x75, 0xb8, 0x5a, 0x3a, 0x66, 0xcf, 0x18, 0x58, 0xd4, 0x2a, 0x3c, 0xee, 0x12, 0x9f, 0x43,
	0x33, 0x4a, 0x84, 0xca, 0x58, 0xa4, 0x9c, 0x53, 0xfd, 0xb1, 0xc2, 0xf8, 0x39, 0xd4, 0xd4, 0xe7,
	0x3c, 0xab, 0xa6, 0x3f, 0x9c, 0xaa, 0xcf, 0xee, 0x32, 0xe7, 0x1f, 0x65, 0x9c, 0xa9, 0x24, 0x73,
	0xea, 0x3d, 0x63, 0xd0, 0xa2, 0x25, 0xd4, 0xfc, 0x13, 0x11, 0x71, 0xa7, 0xa1, 0xfd, 0x3b, 0x80,
	0x31, 0x9c, 0xb2, 0xec, 0x5e, 0x3a, 0xcd, 0x9e, 0x39, 0x68, 0x51, 0x6d, 0xe3, 0x31, 0xd8, 0x4b,
	0x1e, 0x25, 0x19, 0x53, 0xab, 0x44, 0x48, 0xc7, 0xea, 0x99, 0x03, 0x7b, 0xd8, 0x3b, 0x16, 0x61,
	0xfa, 0x18, 0x42, 0x84, 0xca, 0xb6, 0x74, 0x3f, 0xe9, 0xfc, 0x0d, 0xa0, 0xe3, 0x00, 0x8c, 0xc0,
	0xfc, 0x91, 0x6f, 0xb5, 0xa8, 0x16, 0xcd, 0xcd, 0x7c, 0xa6, 0x07, 0xb6, 0xde, 0x70, 0xad, 0x54,
	0x8b, 0xee, 0xc0, 0x77, 0x27, 0xdf, 0x1a, 0xfd, 0x29, 0xb4, 0xf6, 0x55, 0xc6, 0x16, 0xd4, 0xde,
	0x2d, 0x08, 0x7d, 0x8f, 0x9e, 0x61, 0x80, 0xba, 0xeb, 0xdd, 0xf9, 0x6f, 0x09, 0x32, 0x72, 0x7b,
	0xe2, 0x7b, 0x57, 0xee, 0x35, 0x3a, 0xc1, 0x5f, 0x40, 0x7b, 0x67, 0x87, 0x8b, 0xdb, 0xe9, 0x28,
	0x20, 0xc8, 0xec, 0xff, 0x00, 0x9d, 0xf9, 0xea, 0x5e, 0xf0, 0x65, 0xb5, 0xe2, 0xaf, 0xa1, 0x59,
	0xee, 0x4b, 0x0f, 0x62, 0x0f, 0xcf, 0x8e, 0x88, 0xd1, 0x2a, 0x00, 0xbf, 0x02, 0x4b, 0xae, 0xee,
	0x05, 0x53, 0x9b, 0xac, 0x1c, 0xf1, 0xd1, 0xd1, 0xbf, 0x03, 0x7b, 0xcc, 0x54, 0xf4, 0x69, 0xbe,
	0xf9, 0x18, 0xaf, 0x14, 0xbe, 0x86, 0xae, 0xd4, 0xbd, 0xc2, 0xea, 0x0d, 0xad, 0x57, 0x52, 0x39,
	0x86, 0x96, 0xef, 0x45, 0xd1, 0xe5, 0x70, 0x1c, 0x8a, 0xe5, 0x01, 0x9e, 0xad, 0xa4, 0xea, 0x8f,
	0xa1, 0x49, 0xc4, 0x03, 0x5f, 0x27, 0x29, 0xcf, 0xd7, 0x99, 0xb2, 0xed, 0x3a, 0x61, 0x4b, 0x3d,
	0x6d, 0x8b, 0x96, 0xf0, 0x7f, 0x66, 0xfb, 0x00, 0xa8, 0xea, 0xc1, 0x65, 0x9a, 0x08, 0xc9, 0xf1,
	0x4b, 0xa8, 0x4b, 0xc5, 0xd4, 0x66, 0x77, 0x19, 0x35, 0x5a, 0xa0, 0xbc, 0x47, 0xcc, 0xa5, 0x64,
	0xf7, 0xbb, 0x3a, 0x16, 0x2d, 0xe1, 0x7e, 0x77, 0xf3, 0xa0, 0x7b, 0xff, 0x03, 0xb4, 0x35, 0xf7,
	0xaa, 0xf8, 0x0d, 0xbc, 0xac, 0x68, 0x67, 0x85, 0x73, 0x9f, 0xff, 0x97, 0xc7, 0x2a, 0x17, 0x31,
	0xb4, 0x9b, 0x1e, 0x79, 0xb4, 0x06, 0x5b, 0x68, 0x4f, 0x8a, 0x77, 0x4e, 0x1e, 0xb8, 0x50, 0x07,
	0x87, 0x60, 0x3c, 0x75, 0x08, 0x27, 0x7b, 0x87, 0x70, 0x01, 0xc0, 0xf3, 0xcc, 0x50, 0xb0, 0x98,
	0x97, 0x87, 0xa5, 0x3d, 0x1e, 0x8b, 0x0f, 0xa8, 0x9d, 0x1e, 0x52, 0xfb, 0xc3, 0x00, 0x3b, 0xc8,
	0x98, 0x90, 0x2c, 0xca, 0xdf, 0x2e, 0x7e, 0x03, 0x67, 0x47, 0x7b, 0x2d, 0x1e, 0xce, 0x13, 0x2b,
	0xed, 0x1c, 0xae, 0x14, 0x4f, 0x00, 0x1d, 0x53, 0x2c, 0xfe, 0x18, 0x9e, 0xd4, 0xe4, 0x3f, 0x09,
	0xf8, 0x35, 0x74, 0x4a, 0xba, 0xa1, 0x26, 0xa1, 0x19, 0xd9, 0xc3, 0x6e, 0x51, 0xe2, 0x40, 0x2c,
	0xda, 0x8e, 0xf6, 0xe1, 0x57, 0xbf, 0x19, 0x50, 0x9f, 0xef, 0x76, 0x6d, 0x43, 0x63, 0xe1, 0xbd,
	0xf5, 0xfc, 0xef, 0x3d, 0xf4, 0x0c, 0xb7, 0xa0, 0x31, 0x5f, 0x4c, 0x26, 0x64, 0x3e, 0x47, 0xbf,
	0x1b, 0x18, 0x81, 0x3d, 0x1e, 0x4d, 0x43, 0x4a, 0xde, 0x2d, 0xc8, 0x3c, 0x40, 0x3f, 0x99, 0xb8,
	0x03, 0xd6, 0x95, 0x4f, 0xc7, 0xee, 0x74, 0x4a, 0x3c, 0xf4, 0xb3, 0xc6, 0x9e, 0x1f, 0x84, 0x57,
	0xfe, 0xc2, 0x9b, 0xa2, 0x5f, 0x4c, 0x7c, 0x01, 0x4e, 0x11, 0x1d, 0x12, 0x2f, 0x70, 0x83, 0xf7,
	0x61, 0xe0, 0xfb, 0xe1, 0x6c, 0x44, 0xaf, 0x09, 0xfa, 0xd5, 0xc4, 0xe7, 0xf0, 0xc2, 0xf5, 0x02,
	0x42, 0xbd, 0xd1, 0x2c, 0x9c, 0x13, 0x7a, 0x47, 0x68, 0x48, 0x28, 0xf5, 0x29, 0xfa, 0xcb, 0xc4,
	0x5d, 0x38, 0xcb, 0x4b, 0xb9, 0x37, 0xb7, 0x33, 0x72, 0x43, 0xbc, 0x80, 0x4c, 0xd1, 0xdf, 0x26,
	0x76, 0xe0, 0x79, 0x1e, 0xe8, 0x4e, 0x48, 0xb8, 0xf0, 0x46, 0x77, 0x23, 0x77, 0x36, 0x1a, 0xcf,
	0x08, 0xfa, 0xc7, 0xfc, 0x58, 0xd7, 0x34, 0xbf, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x46,
	0xea, 0x13, 0x0a, 0x06, 0x00, 0x00,
}
