apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  imagePullSecrets:
    - name: regsecret
  containers:
    - name: getting-started
      image: registry.cn-hangzhou.aliyuncs.com/isnlan/skaffold
